name: "nixify"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build nix docker base image
      run: |
            nix-build nix/docker.nix --arg artifact 'import ./default.nix' -o dockerImage
            echo "loading resulting nix-built docker image"
            docker load -i dockerImage
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
    - name: Push docker to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
            docker tag ${{ secrets.HEROKU_APP_NAME }} registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
            docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    - name: Release Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
